-- ============================================================
-- Milestone: 09_customer_segmentation.sql
-- TODO: isi sesuai tujuan milestone di docs/roadmap.md
-- Depends on: (isi setelah tau urutan dependency)
-- ============================================================
